### PR TITLE
[FIX] Correct usage modal with path names

### LINKED ISSUE #198: [BUG] "How to get data" tooltip has incorrect file names
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

The docker command shown in the modal when clicking "How to get data" can be run as is

### Current Behavior

`docker run -t -v $(pwd):/data neurobagel/dataget:latest /data/dataset-results.tsv /data/participant-results.tsv /data/output`

is incorrect because the (default) names of the downloaded files are different (i.e. `participant-level-results.tsv` and `dataset-level-results.tsv`). See:

https://github.com/neurobagel/query-tool/blob/566524a828e637b3c333a2dab332f29d653f3771/components/ResultsContainer.vue#L241-L251

### Error message

_No response_

### Environment

_No response_

### How to reproduce

_No response_

### Anything else?

Thanks @ericearl for the report!

### PR DESCRIPTION
**Pull request by surchs**
- fixed path names on the modal
- added the names for the dataset and participant files to the test

Closes: #198

### CODE REVIEW

File: components/ResultsContainer.vue [hunk 1]
```diff
@@ -113,6 +113,7 @@
                 <li>Copy and run the following command:</li>
               </ol>
               <code class="code">{{ code }}</code>
+              <p>Note that the output directory will be created if it does not exist already.</p>
```
Comment (alyssadai) [inline components/ResultsContainer.vue]:
```suggestion
              <p>The downloaded data will be saved in a directory called <code>output</code> in the current directory. Note that the output directory will be created if it does not exist already.</p>
```

**Review by alyssadai — APPROVED** [review]
One 🍒 for clarity, and good to go!
