### PR TITLE
[BUG] Fixed inconsistent behaviour of checkboxes

### LINKED ISSUE #124: [BUG] Old checkbox state in result cards produces blank output file
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Initiating a successive query should produce result cards that are all unchecked, and additionally, downloaded results should have the appropriate subject- or dataset-level tsv data.

### Current Behavior

1. After initiating a query (i.e. querying all the datasets without filters) and selecting a few of the dataset results by clicking on their checkboxes, successive queries afterwards should have those checked checkbox states be cleared to unchecked.
2. When downloading results from such successive queries, proper results should be in the downloaded tsv file.

### Error message

_No response_

### Environment

_No response_

### How to reproduce

1. Query all
2. Select a few datasets in the results by clicking on their checkboxes
3. Alter the query filter(s)
4. Query again
5. Note that checkboxes in the new returned results remain checked
6. Attempt to download subject- or dataset-level datasets from the results
7. Note that the output file is blank except for the header row

### Anything else?

_No response_

### LINKED ISSUE #134: Datasets do not get removed from `downloads` array when new query is run
Once a dataset from the results is selected it is added to the `downloads` array and the only way to remove it from the `downloads` is to unselect it (uncheck the checkbox).
So when a query is run and dataset X from the results is selected (therefore added to the `downloads` array) but not unselected (not removed from the `downloads`) before running another query which may or may not include dataset X in the returned results, X is still included in the `downloads` array.

### PR DESCRIPTION
**Pull request by rmanaem**
Closes #124 
Closes #134 

Changes proposed in this pull request:

- Renamed `selectAll` prop to `isChecked` in the `ResultCard` component
- `updateDownloads` method now uses `event` instead of `refs` in the `ResultCard` component
- Changed the `v-for` `key` to `dataset_uuid` in the `ResultsContainer` component
- Modified the value of the `is-checked` prop passed to `ResultCard` in `ResultsContainer` to check if the `datasetName` is already in the `downloads` array or is `selectAll` set to `true`
- Implemented an integration test to ensure the `downloads` array is wiped every time a query is run
  - documented here in [wiki](https://github.com/neurobagel/documentation/wiki/Cypress-Test-Snippets#provide-different-responses-based-on-a-condition-when-intercepting-requests)
- Implemented a watcher in `ResultsContainer` to wipe the `downloads` array every time `results` is changed i.e. a new query is submitted
- Updated `ResultCard` component test

## Checklist

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[BUG]`, `[DOC]`, `[INFRA]`, `[MAINT]`)
- [x] PR links to Github issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Code is properly formatted

For new features:
- [x] Tests have been added

For bug fixes:
- [x] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

File: components/ResultsContainer.vue [hunk 1]
```diff
@@ -112,6 +112,12 @@ export default {
       return !Object.is(this.results, null) && this.results.length !== 0;
     },
   },
+  watch: {
+    results() {
```
Comment (surchs) [inline components/ResultsContainer.vue:116]: I have mixed feelings here. This is short and works. But there is also a more direct way to figure out if a query was run for us. I.e. "did user click 'query' button". This information is not accessible here, because it's handled by the parent (? or the query form component). But maybe that means the component handling the queries should also be responsible for the `downloads` array. 

I can think of two issues with this solution:
1. If I run the exact same query twice, datasets will (probably ?) not get wiped because `results` are the same (?) - mild inconsistency
2. If we ever start doing what you suggested and manipulate `results` after receiving it from the API (e.g. to manage state), we might be sitting there scratching our heads why all the datasets got wiped.

Neither of them is important, so I'd say let's keep it here. But this also indicates that we may have to think about state management a bit more for this app.

File: cypress/e2e/Checkbox.cy.js [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    dataset_portal_uri: 'https://openneuro.org/datasets/ds001419',
+    num_matching_subjects: 3,
+    subject_data: [],
+    image_modals: ['http://purl.org/nidash/nidm#FlowWeighted', 'http://purl.org/nidash/nidm#T1Weighted'],
+  },
+];
+
+describe('Checkbox', () => {
+  it('Unchecks checked checkboxes after a second query is run.', () => {
+    cy.viewport(2000, 1000);
```
Comment (surchs) [inline cypress/e2e/Checkbox.cy.js:35]: Can you add a comment as to why this is being set here. I remember it's about sizing of viewport resulting in partial occlusion of elements. 

Also: can you open an issue (and link here) about the partial occlusion problem

**Review by surchs — APPROVED** [review]
Very nice PR, thanks @rmanaem. All changes look good to me, but I have some comments on the watcher. Take a look, but this shouldn't hold the PR :cook: 

Sidenote: The preview is nice, but it isn't super useful for this app, because the app gets deployed without a working backend to provide any query results. I wonder if we should just have a `test.neurobagel.org` graph that is small and always on as a solution for all of our testing purposes (at least until we have our `docker compose up` dev envs)

File: cypress/e2e/Checkbox.cy.js (hunk 2 above)
Comment (rmanaem) [reply cypress/e2e/Checkbox.cy.js:35]: See https://github.com/neurobagel/query-tool/issues/136

File: components/ResultsContainer.vue (hunk 1 above)
Comment (rmanaem) [reply components/ResultsContainer.vue:116]: I understand your concern.

> If I run the exact same query twice, datasets will (probably ?) not get wiped because results are the same (?) - mild inconsistency

This doesn't happen. It properly wipes the `downlaods` array even if the `results` are the same.

I noticed another issue, when `selectAll` is checked and another query is run, all datasets are checked but `downloads` is wiped. I resolved this by setting `selectAll` to false along with wiping the `downloads`.
