### PR TITLE
[FIX] Refactored `submitQuery` to resolve the query url construction bug

### LINKED ISSUE #316: [BUG] minimum age gets melted into node API in query
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

I can run a query for a single node and define a minimum age

### Current Behavior

if I set sex, all is well: `https://federate.neurobagel.org/query/?&node_url=https://api.neurobagel.org/&sex=snomed:248153007`

if I set minimum age, this happens: `https://federate.neurobagel.org/query/?&node_url=https://api.neurobagel.org/min_age=1` 

### Error message

federation API rightly complains that 

`"Unrecognized Neurobagel node URL(s): ['https://api.neurobagel.org/min_age=1/']`

### Environment

- any single or multiple node selection except "All"

### How to reproduce

1. Select any node other than "All"
2. define a minimum age
3. watch it break with "Oops"

### Anything else?

see also https://github.com/OpenNeuroOrg/openneuro/issues/2807

most likely this is our culprit: 
https://github.com/neurobagel/query-tool/blob/dadbee332c593f95f5bab9bc037837f2241a6f76/components/QueryForm.vue#L222-L227

i.e. we do not concatenate `min_age` correctly. 

The reason this doesn't break for the "All" node is that we encode "All" as "no node parameter set":

`https://federate.neurobagel.org/query/?min_age=1`

so in this very specific case, `min_age` actually is the first query parameter and gets parsed correctly. This is most likely a leftover thing from when a query tool only ever talked directly to a node API and the federation API didn't exist yet.

### PR DESCRIPTION
**Pull request by rmanaem**
- Closes #316 

Changes proposed in this pull request:

- Refactored `submitQuery` into two methods
  - `constructQueryURL` method which will use `URLSearchParams` to construct
the query param portion of the query URL
  - `submitQuery` will simply call `constructQueryURL` and then make the
axios call
- Updated `APIRequest` test

## Checklist

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [x] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

File: components/QueryForm.vue [hunk 1]
```diff
@@ -209,40 +209,34 @@ export default {
...
+      queryParams.max_age = this.maxAge;
+      queryParams.sex = this.sex;
+      queryParams.diagnosis = this.diagnosis && !this.is_control ? this.diagnosis : null;
+      queryParams.is_control = this.is_control || null;
+      queryParams.min_num_sessions = this.min_num_sessions;
+      queryParams.assessment = this.assessment;
+      queryParams.image_modal = this.modality;
+
+      Object.keys(queryParams).forEach((key) => queryParams[key] == null
+      && delete queryParams[key]);
```
Comment (surchs) [inline components/QueryForm.vue]: :cherries: 
I think this is one of those cases where a classic for loop would be more readable. 
That said, making a filtered object here rather than deleting in place would probably be the cleanest solution. 

e.g.
```js
Object.fromEntries(
  Object.entries(queryParams)
.filter(([param, value]) => value !== null)
```

File: components/QueryForm.vue [hunk 2]
```diff
@@ -209,40 +209,34 @@ export default {
...
+      queryParams.min_age = this.minAge;
+      queryParams.max_age = this.maxAge;
+      queryParams.sex = this.sex;
+      queryParams.diagnosis = this.diagnosis && !this.is_control ? this.diagnosis : null;
+      queryParams.is_control = this.is_control || null;
+      queryParams.min_num_sessions = this.min_num_sessions;
+      queryParams.assessment = this.assessment;
+      queryParams.image_modal = this.modality;
+
+      Object.keys(queryParams).forEach((key) => queryParams[key] == null
```
Comment (surchs) [inline components/QueryForm.vue]:
```
== null
```
is this a sneaky way to catch `undefined`? I'd say let's be explicit then and list both!

**Review by surchs — APPROVED** [review]
thanks a lot for addressing this so quickly @rmanaem! and for finding this much better way of URL parameter construction!

All looks good, but I left a comment on the new URL object filter section, I think we can make that clearer

:cook:

File: components/QueryForm.vue (hunk 2 above)
Comment (rmanaem) [reply components/QueryForm.vue]: Yea but I don't think `undefined` can make its way in there since the defaults are `null` and `v-select` also returns `null` when we remove the selection.

Comment (surchs) [reply components/QueryForm.vue]: Ok then let's use strict equal

File: components/QueryForm.vue (hunk 1 above)
Comment (rmanaem) [reply components/QueryForm.vue]: eslint didn't like this implementation because `param` is unused.

File: components/QueryForm.vue (hunk 2 above)
Comment (rmanaem) [reply components/QueryForm.vue]: switched to strict equal and added the check for `undefined`.
