### PR TITLE
[ENH] Switched to requesting available terms for diagnosis and assessment tool from API

### LINKED ISSUE #261: Switch to requesting available terms for queryable variables from linked API(s)
Now that https://github.com/neurobagel/federation-api/issues/12 is done, the f-API has an endpoint to get available terms from all available n-APIs.

We should now

- [x] Fetch the available terms for diagnosis and assessment tool from the new f-API endpoint
- [x] Decide at what stage of the lifecycle we should make the request
- [x] Remove the old hardcoded diagnosis and assessment options.
- [x] Provide a nice error message (e.g. https://bootstrap-vue.org/docs/components/toast) if either or both of these requests fail and we get zero terms back from the f-API

### PR DESCRIPTION
**Pull request by rmanaem**
- Closes #261 

Changes proposed in this pull request:

- Removed the hardcoded options for diagnosis and assessment tool
- Switched to requesting available terms for diagnosis and assessment tool from API
- Sorted categorical options since the assessment tool terms included a mix of lowercase and uppercase labels
- Implemented logic to display a message when the diagnosis and assessment tool options are not retrieved

## Checklist

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass

For new features:
- [x] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

File: components/CategoricalField.vue [hunk 1]
```diff
@@ -50,6 +50,12 @@ export default {
       selected: this.defaultSelected,
     };
   },
+  computed: {
+    sortedOptions() {
+      const { options } = this;
```
Comment (surchs) [inline components/CategoricalField.vue:56]: we need this because `.sort()` sorts in place and that would break the "do not mutate props" rule, yes? I think that's borderline self-evident. So maybe a "why we do this" comment could help here.

File: components/CategoricalField.vue [hunk 2]
```diff
@@ -50,6 +50,12 @@ export default {
...
+      return options.sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
```
Comment (surchs) [inline components/CategoricalField.vue:57]: can we give this some better names? `a` -> `label`, `b` -> `termURL` or something like that?

File: components/QueryForm.vue [hunk 3]
```diff
@@ -20,7 +20,7 @@
               :value="selectedNodes"
               data-cy="node-field"
               :options="availableNodes"
-              :multiple=true
+              :multiple="true"
```
Comment (surchs) [inline components/QueryForm.vue]: I think this is a bit of a linter-tug-of-war. iirc eslint wants this quoted as string, but v-select wants it as boolean. It seems we can just change to 
```suggestion
              multiple
```
based on https://vue-select.org/guide/values.html#single-multiple, maybe try that.

File: components/QueryForm.vue [hunk 4]
```diff
@@ -52,7 +52,7 @@
         <categorical-field
           name="Diagnosis"
           data-cy="diagnosis-field"
-          :default-selected="Object.keys(categoricalOptions.Diagnosis)[0]"
+          default-selected="All"
```
Comment (surchs) [inline components/QueryForm.vue:55]: I like this, and I know we call the option "All" everywhere, but I wonder if `"Any"` would be more intuitive. Because we're not really searching for one subject who has all of the diagnoses, but rather any. Leaving as note for future issue.

File: cypress/component/QueryForm.cy.js [hunk 5]
```diff
@@ -141,4 +141,14 @@ describe('Query form', () => {
...
   });
+  it('Displays a toast when diagnosis and assessment tool options are not retrieved', () => {
+    props.categoricalOptions.Diagnosis = { All: null };
+    props.categoricalOptions['Assessment tool'] = { All: null };
+    cy.mount(QueryForm, {
+      stubs,
+      propsData: props,
+    });
+    cy.contains('#b-toaster-top-right', 'Failed to retrieve diagnosis options');
+    cy.contains('#b-toaster-top-right', 'Failed to retrieve assessment tool options');
```
Comment (surchs) [inline cypress/component/QueryForm.cy.js:206]: interesting. Why don't you use `cy.get` here first?

File: pages/index.vue [hunk 6]
```diff
@@ -33,73 +33,8 @@ export default {
...
-          'Parkinson\'s disease': 'snomed:49049000',
-          'Progressive supranuclear palsy': 'snomed:192976002',
-          'Separation anxiety': 'snomed:126943008',
-          Schizophrenia: 'snomed:58214004',
-          'Specific spelling disorder': 'snomed:268738002',
-          'Traumatic brain injury': 'snomed:127295002',
-          'Visual impairment': 'snomed:397540003',
         },
         'Assessment tool': {
-          All: null,
```
Comment (surchs) [inline pages/index.vue:59]: :tada:

File: pages/index.vue [hunk 7]
```diff
@@ -113,6 +48,22 @@ export default {
...
+    this.categoricalOptions.Diagnosis = diagnosisOptions;
+
+    const assessmentResponse = await this.$axios.get(`${this.$config.apiQueryURL}attributes/nb:Assessment`);
+    const assessmentOptions = assessmentResponse.data['nb:Assessment'].reduce((tempArray, assessment) => ({
+      ...tempArray,
+      [assessment.Label]: assessment.TermURL,
+    }), {});
+    assessmentOptions.All = null;
+    this.categoricalOptions['Assessment tool'] = assessmentOptions;
+
```
Comment (surchs) [inline pages/index.vue:66]: :tada:

**Review by surchs — APPROVED** [review]
great stuff, thanks @rmanaem :tada:!

Two :cherries: readability things, and then :cook:

**Comment by surchs** [comment]
oh, and please check that all is still happy and running after resolving the merge conflicts

File: components/QueryForm.vue (hunk 4 above)
Comment (rmanaem) [reply components/QueryForm.vue:55]: I like that.

File: components/QueryForm.vue (hunk 3 above)
Comment (rmanaem) [reply components/QueryForm.vue]: Ah yes I didn't notice it finally made its way into a commit.

File: components/CategoricalField.vue (hunk 2 above)
Comment (rmanaem) [reply components/CategoricalField.vue:57]: We could do `label1` and `label2` since `a` and `b` are two elements from the options (labels) array.

File: cypress/component/QueryForm.cy.js (hunk 5 above)
Comment (rmanaem) [reply cypress/component/QueryForm.cy.js:206]: You can use `cy.contains` with a selector to find an element containing a specific text instead of chaining it off `cy.get`.
