### PR TITLE
[FIX] Updated conditions for showing the `OpenNeuro` alert

### LINKED ISSUE #333: Ensure `OpenNeuro` banner only shows up if `OpenNeuro` is in the list of nodes

### PR DESCRIPTION
**Pull request by rmanaem**
- Closes #333 

Changes proposed in this pull request:

- Updated `queryingOpenNeuro` computed property to only show the OpenNeuro alert if
  - It is in the available nodes and `All` is selected
  - It is in the selected nodes
  - `alertDismiss` is false

## Checklist

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

File: pages/index.vue [hunk 1]
```diff
@@ -115,7 +115,9 @@ export default {
       return this.$config.isFederationAPI === undefined ? true : this.$config.isFederationAPI;
     },
     queryingOpenNeuro() {
-      return this.selectedNodes.some((node) => node.NodeName === 'OpenNeuro' || node.NodeName === 'All') && !this.alertDismissed;
+      return (this.selectedNodes.some((node) => node.NodeName === 'OpenNeuro')
+      || (this.selectedNodes.some((node) => node.NodeName === 'All') && this.availableNodes.some((node) => node.NodeName === 'OpenNeuro')))
+      && !this.alertDismissed;
```
Comment (surchs) [inline pages/index.vue:120]: this is very cool!

**Review by surchs — APPROVED** [review]
:tada: very nice PR, thanks @rmanaem!

:cook:
